export const QUICK_REACTIONS = [
  { key: "heart", emoji: "❤️", label: "Love" },
  { key: "fire", emoji: "🔥", label: "Fire" },
  { key: "100", emoji: "💯", label: "One hundred" },
  { key: "wow", emoji: "🤯", label: "Mind blown" },
  { key: "needle", emoji: "📍", label: "Pinned" },
] as const;

export const QUICK_REACTION_KEYS: ReadonlySet<string> = new Set(
  QUICK_REACTIONS.map((reaction) => reaction.key),
);

export type ExtraReaction = {
  emoji: string;
  label: string;
};

type ExtraReactionGroup = {
  key: string;
  icon: string;
  label: string;
  reactions: readonly ExtraReaction[];
};

export const EXTRA_REACTION_GROUPS = [
  {
    key: "faces",
    icon: "😀",
    label: "Faces",
    reactions: [
      { emoji: "😀", label: "Grinning" },
      { emoji: "😄", label: "Big grin" },
      { emoji: "😁", label: "Beaming" },
      { emoji: "😆", label: "Laughing hard" },
      { emoji: "😂", label: "Laughing" },
      { emoji: "🤣", label: "Cracking up" },
      { emoji: "😊", label: "Smiling" },
      { emoji: "😅", label: "Nervous laugh" },
      { emoji: "😇", label: "Angel" },
      { emoji: "🙂", label: "Slight smile" },
      { emoji: "🙃", label: "Upside down" },
      { emoji: "😉", label: "Wink" },
      { emoji: "😍", label: "Adore" },
      { emoji: "🥰", label: "Warm fuzzies" },
      { emoji: "😘", label: "Kiss" },
      { emoji: "😜", label: "Wink tongue" },
      { emoji: "🤪", label: "Zany" },
      { emoji: "😋", label: "Tasty" },
      { emoji: "😎", label: "Cool" },
      { emoji: "🤓", label: "Nerdy" },
      { emoji: "🧐", label: "Inspecting" },
      { emoji: "🤔", label: "Thinking" },
      { emoji: "🤨", label: "Skeptical" },
      { emoji: "😐", label: "Neutral" },
      { emoji: "😑", label: "Expressionless" },
      { emoji: "😶", label: "Speechless" },
      { emoji: "😏", label: "Smirk" },
      { emoji: "😒", label: "Unamused" },
      { emoji: "🙄", label: "Eye roll" },
      { emoji: "😬", label: "Yikes" },
      { emoji: "😮", label: "Surprised" },
      { emoji: "😲", label: "Astonished" },
      { emoji: "😳", label: "Flushed" },
      { emoji: "🥺", label: "Pleading" },
      { emoji: "😢", label: "Sad" },
      { emoji: "😭", label: "Crying" },
      { emoji: "😡", label: "Angry" },
      { emoji: "😤", label: "Huffing" },
      { emoji: "🤮", label: "Nauseated" },
      { emoji: "😈", label: "Mischievous" },
      { emoji: "🤡", label: "Clown" },
      { emoji: "😵", label: "Dizzy face" },
      { emoji: "🥴", label: "Woozy" },
      { emoji: "🫠", label: "Melting" },
      { emoji: "🫡", label: "Salute" },
      { emoji: "😴", label: "Sleepy" },
      { emoji: "🥱", label: "Yawning" },
      { emoji: "🤐", label: "Zipped lips" },
    ],
  },
  {
    key: "hands",
    icon: "👏",
    label: "Hands",
    reactions: [
      { emoji: "👏", label: "Applause" },
      { emoji: "🙌", label: "Raised hands" },
      { emoji: "🙏", label: "Thanks" },
      { emoji: "👍", label: "Thumbs up" },
      { emoji: "👎", label: "Thumbs down" },
      { emoji: "👊", label: "Fist bump" },
      { emoji: "✊", label: "Raised fist" },
      { emoji: "🤛", label: "Left fist" },
      { emoji: "🤜", label: "Right fist" },
      { emoji: "🤝", label: "Handshake" },
      { emoji: "🤞", label: "Fingers crossed" },
      { emoji: "✌️", label: "Peace" },
      { emoji: "🤟", label: "Love you" },
      { emoji: "🤘", label: "Rock on" },
      { emoji: "👌", label: "OK hand" },
      { emoji: "🤌", label: "Chef kiss" },
      { emoji: "👋", label: "Wave" },
      { emoji: "🤙", label: "Call me" },
      { emoji: "👈", label: "Point left" },
      { emoji: "👉", label: "Point right" },
      { emoji: "👆", label: "Point up" },
      { emoji: "👇", label: "Point down" },
      { emoji: "🫵", label: "Point at you" },
      { emoji: "✍️", label: "Writing" },
      { emoji: "💪", label: "Strong" },
      { emoji: "🫶", label: "Heart hands" },
    ],
  },
  {
    key: "music",
    icon: "🎧",
    label: "Music",
    reactions: [
      { emoji: "🎧", label: "Headphones" },
      { emoji: "🎤", label: "Microphone" },
      { emoji: "🎙️", label: "Studio mic" },
      { emoji: "🎸", label: "Guitar" },
      { emoji: "🥁", label: "Drums" },
      { emoji: "🎹", label: "Keyboard" },
      { emoji: "🎺", label: "Trumpet" },
      { emoji: "🎷", label: "Saxophone" },
      { emoji: "🎻", label: "Violin" },
      { emoji: "🪕", label: "Banjo" },
      { emoji: "🪘", label: "Long drum" },
      { emoji: "🎶", label: "Music notes" },
      { emoji: "🎵", label: "Music note" },
      { emoji: "🎼", label: "Score" },
      { emoji: "💿", label: "Disc" },
      { emoji: "📀", label: "DVD" },
      { emoji: "📻", label: "Radio" },
      { emoji: "🎚️", label: "Level slider" },
      { emoji: "🎛️", label: "Control knobs" },
      { emoji: "🪩", label: "Disco ball" },
      { emoji: "🕺", label: "Dancing" },
      { emoji: "💃", label: "Dance" },
      { emoji: "🎬", label: "Clapper" },
      { emoji: "🎭", label: "Drama" },
    ],
  },
  {
    key: "hearts",
    icon: "💜",
    label: "Hearts",
    reactions: [
      { emoji: "💘", label: "Arrow heart" },
      { emoji: "💝", label: "Gift heart" },
      { emoji: "💖", label: "Sparkle heart" },
      { emoji: "💗", label: "Growing heart" },
      { emoji: "💓", label: "Beating heart" },
      { emoji: "💕", label: "Two hearts" },
      { emoji: "💞", label: "Revolving hearts" },
      { emoji: "💟", label: "Heart decoration" },
      { emoji: "❣️", label: "Heart exclamation" },
      { emoji: "💔", label: "Broken heart" },
      { emoji: "❤️‍🔥", label: "Heart on fire" },
      { emoji: "❤️‍🩹", label: "Mending heart" },
      { emoji: "🩷", label: "Pink heart" },
      { emoji: "🧡", label: "Orange heart" },
      { emoji: "💛", label: "Yellow heart" },
      { emoji: "💚", label: "Green heart" },
      { emoji: "💙", label: "Blue heart" },
      { emoji: "💜", label: "Purple heart" },
      { emoji: "🤎", label: "Brown heart" },
      { emoji: "🖤", label: "Black heart" },
      { emoji: "🩶", label: "Gray heart" },
      { emoji: "🤍", label: "White heart" },
    ],
  },
  {
    key: "spark",
    icon: "✨",
    label: "Spark",
    reactions: [
      { emoji: "✨", label: "Sparkles" },
      { emoji: "⭐", label: "Star" },
      { emoji: "🌟", label: "Glowing star" },
      { emoji: "💫", label: "Dizzy" },
      { emoji: "💥", label: "Boom" },
      { emoji: "💢", label: "Anger pop" },
      { emoji: "💦", label: "Sweat drops" },
      { emoji: "💨", label: "Dash" },
      { emoji: "💤", label: "Sleep" },
      { emoji: "⚡", label: "Electric" },
      { emoji: "🌈", label: "Rainbow" },
      { emoji: "☀️", label: "Sun" },
      { emoji: "🌙", label: "Moon" },
      { emoji: "☁️", label: "Cloud" },
      { emoji: "🌊", label: "Wave" },
      { emoji: "🌀", label: "Spiral" },
      { emoji: "🎯", label: "Bullseye" },
      { emoji: "🏆", label: "Trophy" },
      { emoji: "🥇", label: "Gold medal" },
      { emoji: "🎉", label: "Party popper" },
      { emoji: "🎊", label: "Confetti" },
      { emoji: "🥳", label: "Partying" },
      { emoji: "💎", label: "Gem" },
      { emoji: "🚀", label: "Rocket" },
      { emoji: "🧨", label: "Firecracker" },
      { emoji: "🪄", label: "Magic wand" },
      { emoji: "🔮", label: "Crystal ball" },
    ],
  },
  {
    key: "vibes",
    icon: "🍿",
    label: "Vibes",
    reactions: [
      { emoji: "👀", label: "Eyes" },
      { emoji: "🧠", label: "Brainy" },
      { emoji: "💡", label: "Idea" },
      { emoji: "📝", label: "Notes" },
      { emoji: "✅", label: "Check" },
      { emoji: "❌", label: "Cross" },
      { emoji: "📚", label: "Studious" },
      { emoji: "🗣️", label: "Talk" },
      { emoji: "💬", label: "Comment" },
      { emoji: "📣", label: "Announcement" },
      { emoji: "🔊", label: "Loud" },
      { emoji: "🔇", label: "Muted" },
      { emoji: "🍿", label: "Popcorn" },
      { emoji: "☕", label: "Coffee" },
      { emoji: "🍷", label: "Wine" },
      { emoji: "🍻", label: "Cheers" },
      { emoji: "🥂", label: "Toast" },
      { emoji: "🍾", label: "Celebration" },
      { emoji: "🧂", label: "Salty" },
      { emoji: "🧊", label: "Ice cold" },
      { emoji: "🛋️", label: "Couch" },
      { emoji: "🧯", label: "Extinguisher" },
      { emoji: "🧪", label: "Experiment" },
      { emoji: "🧭", label: "Compass" },
      { emoji: "🧱", label: "Brick" },
      { emoji: "💩", label: "Pile of poo" },
      { emoji: "💀", label: "Dead laughing" },
      { emoji: "☠️", label: "Skull and crossbones" },
      { emoji: "🍑", label: "Peach" },
      { emoji: "🍆", label: "Eggplant" },
      { emoji: "🪦", label: "Dead" },
      { emoji: "🏁", label: "Finish" },
    ],
  },
] as const satisfies readonly ExtraReactionGroup[];

export const EXTRA_REACTIONS: ExtraReaction[] = EXTRA_REACTION_GROUPS.flatMap(
  (group): readonly ExtraReaction[] => group.reactions,
);

export function getReactionEmoji(value: string) {
  return QUICK_REACTIONS.find((reaction) => reaction.key === value)?.emoji ?? value;
}

export function getReactionKey(value: string) {
  return QUICK_REACTIONS.find(
    (reaction) => reaction.key === value || reaction.emoji === value,
  )?.key;
}

export function getEmojiReactionLabel(emoji: string) {
  return EXTRA_REACTIONS.find((reaction) => reaction.emoji === emoji)?.label ?? "Emoji reaction";
}

export function normalizeEmojiSearch(value: string) {
  return value.trim().toLocaleLowerCase();
}
